//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GDAy.rc
//
#define ID_YESALL                       7
#define ID_NOALL                        8
#define IDS_TT_GRIDFILE                 100
#define IDS_TT_IDLEMESSAGE              101
#define IDS_TT_INTERACTIVEOUTPUT        102
#define IDS_TT_NULL                     103
#define IDB_DNR_LOGO                    104
#define IDB_GDA_LOGO                    105
#define IDB_GDAY_LOGO                   106
#define IDD_ABOUTBOX                    108
#define IDD_COORDINATE_SYSTEM           109
#define IDD_GDAY_DIALOG                 110
#define IDD_GRID_AND_PARAMS             111
#define IDD_GRID_PROPERTIES             112
#define IDD_OPTIONS_VIEW                113
#define IDD_OPTIONS_PAGE2               114
#define IDD_OPTIONS_OUTFILE             114
#define IDD_OPTIONS_PAGE3               115
#define IDD_OPTIONS_LOGFILE             115
#define IDD_POINT_FILE                  116
#define IDD_POINT_FILE_PROGRESS         117
#define IDD_POINT_FILE_ZONE             118
#define IDD_STATION_NAME                119
#define IDR_GDAY_ICON                   121
#define IDR_MAIN_MENU                   122
#define IDB_NRM_LOGO                    123
#define IDR_STATUS_OUTFILE_POPUP        125
#define IDR_STATUS_GRID_POPUP           126
#define IDR_POPUP                       127
#define IDR_GDA_LOGO                    130
#define IDB_BITMAP1                     131
#define IDR_GDA                         136
#define IDD_POINT_DIR                   141
#define IDD_POINT_DIR_CREATEDIR         143
#define IDD_PROGRESS                    148
#define IDR_NRM                         150
#define IDB_DNRM                        155
#define IDR_DNRM                        157
#define IDR_VIEWLOG                     159
#define IDD_GRID_DEFAULT_SELECT         160
#define IDB_GDA2020_LOGO                167
#define IDC_STATIC_LOGO					168
#define IDC_STATIC_GROUP_OUT			169
#define IDC_ADD_STN_NAME                1001
#define IDC_AUTO_INC                    1002
#define IDC_AUTO_NAME                   1003
#define IDC_COMPUTE                     1004
#define IDC_CREATE_OUTPUT_FILE          1005
#define IDC_CUSTOM_NAME                 1006
#define IDC_DMS_FORMAT                  1007
#define IDC_EAST                        1008
#define IDC_EAST2                       1009
#define IDC_EAST_LONG                   1010
#define IDC_FILENAME                    1011
#define IDC_FILETYPE                    1012
#define IDC_GRID_BROWSE                 1013
#define IDC_GRID_FILENAME               1014
#define IDC_HEADER                      1015
#define IDC_HP_IN                       1016
#define IDC_LONG                        1017
#define IDC_HP_OUT                      1018
#define IDC_IN_DATUM_DESC               1019
#define IDC_IN_DDEG                     1020
#define IDC_DDEG                        1021
#define IDC_IN_DMIN                     1022
#define IDC_DMIN                        1023
#define IDC_IN_DMS                      1024
#define IDC_DMS                         1025
#define IDC_IN_FORMAT                   1026
#define IDC_IN_PROJ_DESC                1027
#define IDS_STRING1022                  1028
#define IDC_INPUT_BROWSE                1029
#define IDC_INPUT_DATUM                 1030
#define IDC_INPUT_FILENAME              1031
#define IDC_INPUT_HP                    1032
#define IDC_INPUT_PROJ                  1033
#define IDC_INPUT_SEP                   1034
#define IDC_INPUT_VAR1                  1035
#define IDC_INPUT_VAR2                  1036
#define IDC_INPUT_VAR3                  1037
#define IDC_LAT_EAST                    1038
#define IDC_LAT                         1039
#define IDC_LAT2                        1040
#define IDC_LAT_EAST2                   1041
#define IDC_LOG_FILE_CHANGE             1042
#define IDC_LOG_FILEPATH                1043
#define IDC_LOG_VIEW                    1044
#define IDC_LONG2                       1045
#define IDC_LONG_NTH                    1046
#define IDC_LONG_NTH2                   1047
#define IDC_METRES_PREC                 1048
#define IDC_METRES_SPIN                 1049
#define IDC_NORTH                       1050
#define IDC_NORTH2                      1051
#define IDC_NORTH_LAT                   1052
#define IDC_NUMSUBGRIDS                 1053
#define IDC_OUT_DATUM_DESC              1054
#define IDC_OUT_DDEG                    1055
#define IDC_OUT_DMIN                    1056
#define IDC_OUT_DMS                     1057
#define IDC_OUT_FORMAT                  1058
#define IDC_OUT_PROJ_DESC               1059
#define IDC_OUTPUT_BROWSE               1060
#define IDC_OUTPUT_DATUM                1061
#define IDC_OUTPUT_FILE_CHANGE          1062
#define IDC_OUTPUT_FILENAME             1063
#define IDC_OUTPUT_FILEPATH             1064
#define IDC_OUTPUT_HEADER               1065
#define IDC_OUTPUT_HP                   1066
#define IDC_OUTPUT_PROJ                 1067
#define IDC_OUTPUT_SEP                  1068
#define IDC_OUTPUT_VAR1                 1069
#define IDC_OUTPUT_VAR2                 1070
#define IDC_OUTPUT_VAR3                 1071
#define IDC_PARAM                       1072
#define IDC_PERCENT_COMPLETE            1073
#define IDC_PFILE_ZONE                  1074
#define IDC_PNUM_FRAME                  1075
#define IDC_PNUM_VAR                    1076
#define IDC_POINT_NUM                   1077
#define IDC_POINT_START_NUM             1078
#define IDC_POS_NEG_FORMAT              1079
#define IDC_POS_SOUTH                   1080
#define IDC_PREC_EAST                   1082
#define IDC_PREC_LATEAST                1083
#define IDC_PREC_LAT                    1084
#define IDC_PREC_LONGNORTH              1085
#define IDC_PREC_LONG                   1086
#define IDC_PREC_NORTH                  1087
#define IDC_PROGRESS_BAR                1088
#define IDC_PROMPT                      1089
#define IDC_PROMPT_STN_NAME             1090
#define IDC_PT_NUMBER                   1091
#define IDC_SECONDS_PREC                1092
#define IDC_SECONDS_SPIN                1093
#define IDC_SOUTH                       1094
#define IDC_SOUTH_LAT                   1095
#define IDC_STATION_NAME                1096
#define IDC_SUBGRID_NAME                1097
#define IDC_SYSTEM_FROM                 1098
#define IDC_SYSTEM_TO                   1099
#define IDC_VERSION                     1104
#define IDC_WEST                        1105
#define IDC_WEST_LONG                   1106
#define IDC_ZONE                        1107
#define IDC_ZONE2                       1108
#define IDP_DEFNAME                     1109
#define IDP_DEVELOPER                   1110
#define IDP_STARTAT                     1111
#define IDP_VERSION                     1112
#define IDC_INPUTBOX                    1114
#define IDC_OUTPUTBOX                   1115
#define IDC_FILEIN                      1116
#define IDC_FILEOUT                     1117
#define IDC_INPUT_FORMAT                1118
#define IDC_OUTPUT_FORMAT               1119
#define IDC_DIRIN                       1120
#define IDC_INPUT_DIR                   1121
#define IDC_DIR_LOOKIN                  1122
#define IDC_DIR_SAVEIN                  1123
#define IDC_OUTPUT_DIR                  1124
#define IDC_IN_GEO_BOX                  1125
#define IDC_IN_FILE_BOX                 1126
#define IDC_OUT_GEO_BOX                 1127
#define IDC_OUT_FILE_BOX                1128
#define IDC_RECURSE                     1129
#define IDC_DIRICON                     1130
#define ID_NO                           1131
#define IDC_INCONQUESTION               1132
#define IDC_ICONQUESTION                1132
#define IDC_DIR_PROMPT                  1133
#define ID_YES                          1134
#define IDC_TRANSFORMING_DIR            1135
#define IDC_DIR_TO_DIR                  1135
#define IDC_DIR_PROGRESS                1136
#define IDC_BUTTON1                     1139
#define IDC_DIRMSG                      1140
#define IDC_OUTZONE_PROMPT              1142
#define IDC_SEPARATOR                   1143
#define IDC_GRIDFILE_REMINDER           1144
#define IDM_FILE_EXPORTTOASCII          32773
#define IDM_FILE_EXPORTTOBINARY         32774
#define IDM_FILE_GRIDEX                 32775
#define IDM_FILE_GRIDFILE               32776
#define IDM_FILE_GRIDPROP               32777
#define IDM_FILE_OUTPUT                 32779
#define IDM_FILE_TRANS_POINTSFILE       32780
#define IDM_FILE_VIEW                   32781
#define IDM_HELP_ABOUTGDAY              32782
#define IDM_TOOLS_COORD_SYSTEM          32783
#define IDM_TOOLS_OPTIONS               32784
#define IDM_TRANSFORM_GDA20TOGDA94      32785
#define IDM_FILE_TRANS_DIRECTORY        32789
#define IDM_LOGFILEVIEW                 32792
#define ID_HELP_SEARCH                  32794
#define ID_HELP_CONTENTS                32797
#define IDM_TRANSFORM_GDA94TOGDA20      32798
#define IDS_TT_OUTDATUM                 57671
#define IDS_TT_INDATUM                  57672
#define IDS_TT_READY                    57673
#define WM_THREADFINISHED               57674

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
